# Generated by Django 2.2.14 on 2021-02-15 12:41

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KWLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('k', 'know'), ('w', 'wonder'), ('l', 'learned')], max_length=1)),
                ('sort_order', models.IntegerField()),
                ('user', models.CharField(max_length=500)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(blank=True, default=None, max_length=255, null=True)),
                ('scope_id', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
