# Generated by Django 2.2.14 on 2021-02-16 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kwl_djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwlmodel',
            name='dropped_in',
            field=models.CharField(blank=True, choices=[('k', 'know'), ('w', 'wonder'), ('l', 'learned')], max_length=1),
        ),
        migrations.AddField(
            model_name='kwlmodel',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kwlmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
